# =========================================================
# [FILE] settings.py
# [PATH] <project_root>/config/settings.py
#
# このファイルは何？
# - Django全体の設定ファイルです（DB/アプリ/cron/各種定数など）。
#
# 今回の修正：
# 1) tradeai アプリを追加
# =========================================================

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import environ
import dotenv
from dotenv import load_dotenv

# === env 読み込み（.env） ===
env = environ.Env()
env.read_env(env.str("ENV_PATH", ".env"))

dotenv.load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))
load_dotenv()

# === パス基点 ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === 基本設定 ===
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-CHANGE-ME")
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "gorozooo.com",
    "www.gorozooo.com",
    "192.168.1.16",
]

CSRF_TRUSTED_ORIGINS = [
    "https://gorozooo.com",
    "https://www.gorozooo.com",
]

# === アプリケーション ===
INSTALLED_APPS = [
    # Django標準
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",

    # 追加
    "django_htmx",
    "django.contrib.humanize",
    "django_crontab",

    # 自作アプリ
    "portfolio",
    "aiapp.apps.AiappConfig",
    "tradeai.apps.TradeaiConfig",

    # 自動売買
    "autotrade.apps.AutotradeConfig",

    # 家計簿
    "kakeibo.apps.KakeiboConfig",

    # 指標
    "shihyo.apps.ShihyoConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # request.htmx
    "django_htmx.middleware.HtmxMiddleware",

    # あなた専用エリア制御
    "config.middleware.owner_only.OwnerOnlyMiddleware",
]

ROOT_URLCONF = "config.urls"

# === テンプレート ===
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# =========================================================
# DB（SQLite）
# - default: 既存（web/他cronが使うメインDB）
# - autotrade: autotrade専用DB
# =========================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 30,
        },
    },
    "autotrade": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "autotrade.sqlite3",
        "OPTIONS": {
            "timeout": 30,
        },
    },
}

# autotradeアプリだけ autotrade DB を使う
DATABASE_ROUTERS = [
    "config.db_router.AutotradeRouter",
]

# SQLite を WAL + busy_timeout に
import config.sqlite_setup  # noqa: F401

# === パスワードバリデータ ===
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# === i18n/L10n ===
LANGUAGE_CODE = "ja"
TIME_ZONE = "Asia/Tokyo"
USE_I18N = True
USE_TZ = True

# === Static ===
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ログイン/ログアウト
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# === メディア ===
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 銘柄名の上書き
TSE_NAME_OVERRIDES = {
    "167A": "リョーサン菱洋ホールディングス",
    "285A": "キオクシアホールディングス",
    "186A": "アストロスケールホールディングス",
    "324A": "ブッキングリゾート",
}

# === LINE（環境変数で管理）===
LINE_CHANNEL_ACCESS_TOKEN = os.getenv("LINE_CHANNEL_ACCESS_TOKEN", "")
LINE_CHANNEL_SECRET = os.getenv("LINE_CHANNEL_SECRET", "")
LINE_USER_ID = os.getenv("LINE_USER_ID", "")

# === メール（環境変数で管理）===
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", EMAIL_HOST_USER)

# セクター指標
ADVISOR_SECTOR_SYMBOLS = {
    "情報・通信": "1306.T",
    "電気機器": "6981.T",
    "銀行": "8316.T",
}
ADVISOR_SECTOR_LOOKBACK_DAYS = 90

# === HTTPS/セキュリティ（DEBUG時は無効化）===
if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

# === AIAPP ===
AIAPP_UNIVERSE_LIMIT = 200
AIAPP_EQUITY = 3_000_000.0
AIAPP_LOT = 100
AIAPP_PRO_EQUITY_YEN = 5_000_000

# ==========================
# ACCESS CONTROL
# ==========================
STOCKS_OWNER_USERNAME = os.getenv("STOCKS_OWNER_USERNAME", "gorozooo")
KAKEIBO_GROUP_NAME = os.getenv("KAKEIBO_GROUP_NAME", "kakeibo_users")

# ==========================
# AUTOTRADE（確定仕様）
# ==========================
AUTOTRADE_BASE_EQUITY_YEN = 1_000_000

AUTOTRADE_RISK_TRADE_PCT = 0.0015  # 0.15%
AUTOTRADE_RISK_DAY_PCT = 0.01      # 1%

AUTOTRADE_MAX_POSITIONS_FULL = 2
AUTOTRADE_MAX_TRADES_FULL = 6

AUTOTRADE_MAX_POSITIONS_LIGHT = 1
AUTOTRADE_MAX_TRADES_LIGHT = 3

AUTOTRADE_SESSION_START = "09:00"
AUTOTRADE_SESSION_END = "15:00"
AUTOTRADE_FORCE_CLOSE = "15:25"
AUTOTRADE_ALLOW_HOLD_PAST_SESSION_END = True

AUTOTRADE_MAX_TRADES_BREAKOUT = 4
AUTOTRADE_MAX_TRADES_VWAP = 2

AUTOTRADE_RR_BREAKOUT = 2.0
AUTOTRADE_RR_VWAP = 1.5

AUTOTRADE_BT_WINDOWS = [20, 40, 60]

AUTOTRADE_GATE = {
    "dd_limits": {20: 0.02, 40: 0.03, 60: 0.04},
    "pf_min": 1.05,
    "min_trades": {20: 10, 40: 20, 60: 30},
}

AUTOTRADE_SLIPPAGE_PCT = 0.0002  # 0.02%

AUTOTRADE_DEFAULT_CANDIDATES = [
    "7203.T","6758.T","9432.T","9984.T","8306.T","8316.T","8035.T","8058.T",
    "6861.T","6501.T","6503.T","7267.T","8801.T","8802.T","9020.T","9022.T",
    "4502.T","4503.T","4519.T","4568.T","2914.T","6098.T","4063.T","6723.T",
    "7011.T","9101.T","9104.T","8411.T","8604.T","8601.T","5401.T","5406.T",
]

AUTOTRADE_MORNING_AGG = "wmean"

# ==========================
# AUTOTRADE CRON Safety
# ==========================
AUTOTRADE_CRON_LOCK_DIR = "/tmp"
AUTOTRADE_CRON_MAX_RUNTIME_SEC = 50

# ==========================
# AUTOTRADE AUTO-TUNE（全ノブ試行の探索範囲）
# ==========================
# RR
AUTOTRADE_TUNE_RR_MIN = 1.0
AUTOTRADE_TUNE_RR_MAX = 3.5
AUTOTRADE_TUNE_RR_STEP_STOP = 0.20
AUTOTRADE_TUNE_RR_STEP_LIGHT = 0.15
AUTOTRADE_TUNE_RR_STEP_FULL = 0.10

# 損切り幅（0.0025 = 0.25%）
AUTOTRADE_TUNE_STOP_PCT_MIN = 0.0025
AUTOTRADE_TUNE_STOP_PCT_MAX = 0.0120

# ブレイク判定本数
AUTOTRADE_TUNE_LOOKBACK_MIN = 6
AUTOTRADE_TUNE_LOOKBACK_MAX = 30

# 最大保有（5分足の本数）
AUTOTRADE_TUNE_MAX_HOLD_BARS_MIN = 3
AUTOTRADE_TUNE_MAX_HOLD_BARS_MAX = 18

# SMA日数
AUTOTRADE_TUNE_SMA_MIN = 10
AUTOTRADE_TUNE_SMA_MAX = 75

# ==========================
# django-crontab（ジョブ）
# ==========================
CRONJOBS = [
    # 朝準備（ACTIVE判定 + 毎朝チューニング候補作成）
    ("30 6 * * 1-5", "autotrade.jobs.morning_prepare.run", ">> /tmp/autotrade_morning.log 2>&1"),

    # 場前の戦略確定
    ("55 8 * * 1-5", "autotrade.jobs.decide_strategy.run", ">> /tmp/autotrade_decide.log 2>&1"),

    # 場中デモ/本番準備
    ("*/1 9-15 * * 1-5", "autotrade.jobs.intraday_trade.run", ">> /tmp/autotrade_intraday_trade.log 2>&1"),
    ("*/1 9-15 * * 1-5", "autotrade.jobs.intraday_guard.run", ">> /tmp/autotrade_intraday_guard.log 2>&1"),

    # 引け処理
    ("30 15 * * 1-5", "autotrade.jobs.end_of_day.run", ">> /tmp/autotrade_eod.log 2>&1"),

    # 引け後STOP救済（STOP日のみ、旧ACTIVEより良い候補があれば昇格）
    ("35 15 * * 1-5", "autotrade.jobs.eod_stop_rescue.run", ">> /tmp/autotrade_eod_stop_rescue.log 2>&1"),
]