"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import environ
import dotenv
from dotenv import load_dotenv

# === env 読み込み（.env） ===
env = environ.Env()
env.read_env(env.str("ENV_PATH", ".env"))

dotenv.load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))
load_dotenv()

# === パス基点 ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === 基本設定 ===
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-CHANGE-ME")
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "gorozooo.com",
    "www.gorozooo.com",
    "192.168.1.16",
]

CSRF_TRUSTED_ORIGINS = [
    "https://gorozooo.com",
    "https://www.gorozooo.com",
]

# === アプリケーション ===
INSTALLED_APPS = [
    # Django標準
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",

    # 追加
    "django_htmx",
    "django.contrib.humanize",
    "django_crontab",

    # 自作アプリ
    "portfolio",
    "aiapp.apps.AiappConfig",

    # ★ 自動売買（新規）
    "autotrade.apps.AutotradeConfig",

    # ★ 家計簿（新規）
    "kakeibo.apps.KakeiboConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # ★ 追加: request.htmx など
    "django_htmx.middleware.HtmxMiddleware",
    
    # ★ 追加：あなた専用エリア制御（aiapp/autotrade/portfolio/admin をブロック）
    "config.middleware.owner_only.OwnerOnlyMiddleware",
]

ROOT_URLCONF = "config.urls"

# === テンプレート ===
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# === DB（開発: SQLite）===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# === パスワードバリデータ ===
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# === i18n/L10n ===
LANGUAGE_CODE = "ja"
TIME_ZONE = "Asia/Tokyo"
USE_I18N = True
USE_TZ = True

# === Static ===
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ログイン/ログアウト
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# === メディア ===
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ★ 銘柄名の上書き（yfinanceが英名になるケースの対策）
TSE_NAME_OVERRIDES = {
    "167A": "リョーサン菱洋ホールディングス",
    "285A": "キオクシアホールディングス",
    "186A": "アストロスケールホールディングス",
    "324A": "ブッキングリゾート",
}

# === LINE（環境変数で管理）===
LINE_CHANNEL_ACCESS_TOKEN = os.getenv("LINE_CHANNEL_ACCESS_TOKEN", "")
LINE_CHANNEL_SECRET = os.getenv("LINE_CHANNEL_SECRET", "")
LINE_USER_ID = os.getenv("LINE_USER_ID", "")

# === メール（環境変数で管理）===
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", EMAIL_HOST_USER)

# セクター指標（既存）
ADVISOR_SECTOR_SYMBOLS = {
    "情報・通信": "1306.T",
    "電気機器": "6981.T",
    "銀行": "8316.T",
}
ADVISOR_SECTOR_LOOKBACK_DAYS = 90

# === HTTPS/セキュリティ（DEBUG時は無効化）===
if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

# === AIAPP 既存 ===
AIAPP_UNIVERSE_LIMIT = 200
AIAPP_EQUITY = 3_000_000.0
AIAPP_LOT = 100
AIAPP_PRO_EQUITY_YEN = 5_000_000

# ==========================
# ★ ACCESS CONTROL（追加）
# ==========================
# 株アプリは「あなた1人だけ」通すための固定ユーザー名
STOCKS_OWNER_USERNAME = os.getenv("STOCKS_OWNER_USERNAME", "gorozooo")

# 家計簿アプリは「夫婦だけ」通すためのグループ名
KAKEIBO_GROUP_NAME = os.getenv("KAKEIBO_GROUP_NAME", "kakeibo_users")

# ==========================
# ★ AUTOTRADE（確定仕様）
# ==========================
AUTOTRADE_BASE_EQUITY_YEN = 1_000_000

# 資金管理（総資産連動）
AUTOTRADE_RISK_TRADE_PCT = 0.0015  # 0.15%
AUTOTRADE_RISK_DAY_PCT = 0.01      # 1%

AUTOTRADE_MAX_POSITIONS_FULL = 2
AUTOTRADE_MAX_TRADES_FULL = 6

AUTOTRADE_MAX_POSITIONS_LIGHT = 1
AUTOTRADE_MAX_TRADES_LIGHT = 3

AUTOTRADE_SESSION_START = "09:00"
AUTOTRADE_SESSION_END = "15:00"
AUTOTRADE_FORCE_CLOSE = "15:25"

# 戦略回数配分
AUTOTRADE_MAX_TRADES_BREAKOUT = 4
AUTOTRADE_MAX_TRADES_VWAP = 2

# RR
AUTOTRADE_RR_BREAKOUT = 2.0
AUTOTRADE_RR_VWAP = 1.5

# バックテスト期間
AUTOTRADE_BT_WINDOWS = [20, 40, 60]

# ゲート判定（DD / PF / 回数）
AUTOTRADE_GATE = {
    "dd_limits": {20: 0.02, 40: 0.03, 60: 0.04},
    "pf_min": 1.05,
    "min_trades": {20: 10, 40: 20, 60: 30},
}

# スリッページ（不利側固定）
AUTOTRADE_SLIPPAGE_PCT = 0.0002  # 0.02%

# 銘柄候補（ここは後で強化：今は安定稼働優先のフォールバック）
# media/autotrade/universe_candidates.txt があればそれを優先して読む
AUTOTRADE_DEFAULT_CANDIDATES = [
    "7203.T","6758.T","9432.T","9984.T","8306.T","8316.T","8035.T","8058.T",
    "6861.T","6501.T","6503.T","7267.T","8801.T","8802.T","9020.T","9022.T",
    "4502.T","4503.T","4519.T","4568.T","2914.T","6098.T","4063.T","6723.T",
    "7011.T","9101.T","9104.T","8411.T","8604.T","8601.T","5401.T","5406.T",
]

#"wmean"（売買代金重み）
AUTOTRADE_MORNING_AGG = "wmean"

# ==========================
# ★ django-crontab（ジョブ）
# ==========================
CRONJOBS = [
    # 毎朝：銘柄選定＆バックテスト（6:30）
    ("30 6 * * 1-5", "autotrade.jobs.morning_prepare.run", ">> /tmp/autotrade_morning.log 2>&1"),
    
    # 9:30：戦略決定＆ゲート確定（9:30）
    ("55 8 * * 1-5", "autotrade.jobs.decide_strategy.run", ">> /tmp/autotrade_decide.log 2>&1"),

    # ★ 追加：場中ガード（毎分）
    ("*/1 9-15 * * 1-5", "autotrade.jobs.intraday_guard.run", ">> /tmp/autotrade_intraday_guard.log 2>&1"),

    # 15:10：日次クローズ（15:10）
    ("10 15 * * 1-5", "autotrade.jobs.end_of_day.run", ">> /tmp/autotrade_eod.log 2>&1"),
]