"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

# === パス基点 ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === 基本設定 ===
# ※ 本番では環境変数で管理しましょう（開発中はこのままでOK）
SECRET_KEY = 'django-insecure-(f8%22e=p67$pa(7pd!%z3p7f$6w8z)_%o7lgti6i#8pi_%(59'
#DEBUG = False
DEBUG = True

# 開発中: 空でOK / 本番(ConoHa等): ドメイン or IP を追加
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "gorozooo.com", "www.gorozooo.com", "192.168.1.16"]

# === アプリケーション ===
INSTALLED_APPS = [
    # Django標準
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    # ここに自作アプリを足していきます（作ったらコメントアウト解除）
     'portfolio',
     'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# === テンプレート ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ← ここがポイント：プロジェクト直下の templates/ を読む
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # デバッグやrequestなどの共通コンテキスト
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# === データベース（開発: SQLite）===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# === パスワードバリデータ ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# === i18n/L10n ===
# ← ここがポイント：日本語・日本時間に変更
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True  # DBはUTCで保存、表示はAsia/Tokyo

# === Static（CSS/JS/画像）===
STATIC_URL = 'static/'

# （集約先フォルダ）
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# ← ここがポイント：プロジェクト直下の static/ を読む
STATICFILES_DIRS = [BASE_DIR / 'static']

# 既定の主キー
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ログイン/ログアウト
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

TSE_NAME_OVERRIDES = {
    "167A": "リョーサン菱洋ホールディングス",  
    # 追加したいコードがあればここに並べる
}

