# Generated by Django 5.0.7 on 2025-08-27 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タブ名')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='アイコン')),
                ('url_name', models.CharField(blank=True, max_length=200, verbose_name='内部ビュー名 or URL')),
                ('link_type', models.CharField(choices=[('view', '内部ビュー名'), ('url', '外部リンク'), ('dummy', 'ダミーリンク')], default='view', max_length=10, verbose_name='リンクタイプ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='RealizedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='設定画面パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
                ('ticker', models.CharField(max_length=4, verbose_name='証券コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('account_type', models.CharField(default='現物', max_length=10, verbose_name='口座区分')),
                ('sector', models.CharField(default='', max_length=50, verbose_name='セクター')),
                ('shares', models.PositiveIntegerField(verbose_name='株数')),
                ('unit_price', models.FloatField(verbose_name='取得単価')),
                ('total_cost', models.PositiveIntegerField(verbose_name='取得額')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, unique=True, verbose_name='証券コード')),
                ('name', models.CharField(max_length=200, verbose_name='銘柄名')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='33業種')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='サブメニュー名')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='portfolio.bottomtab')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
