# Generated by Django 5.0.7 on 2025-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='broker',
            field=models.CharField(choices=[('楽天', '楽天'), ('松井', '松井'), ('moomoo', 'moomoo'), ('SBI', 'SBI')], default='楽天', max_length=20, verbose_name='証券会社'),
        ),
    ]
