# Generated by Django 5.0.7 on 2025-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='設定画面パスワード')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bottomtab',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='bottomtab',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='bottomtab',
            name='icon',
            field=models.CharField(default='fa-home', max_length=50),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='url_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
