# Generated by Django 5.0.7 on 2025-08-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_settingspassword_alter_bottomtab_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomtab',
            name='link_type',
            field=models.CharField(choices=[('view', '内部ビュー名'), ('url', '外部リンク'), ('dummy', 'ダミーリンク')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='url_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
