# Generated by Django 5.0.7 on 2025-08-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stock_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='note',
        ),
    ]
