# Generated by Django 5.0.7 on 2025-08-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_bottomtab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottomtab',
            options={},
        ),
        migrations.RemoveField(
            model_name='bottomtab',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bottomtab',
            name='is_submenu',
        ),
        migrations.RemoveField(
            model_name='bottomtab',
            name='url_name',
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='icon_class',
            field=models.CharField(default='fa fa-circle', max_length=50),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='portfolio.bottomtab')),
            ],
        ),
    ]
