# Generated by Django 5.0.7 on 2025-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_stock_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='メモ'),
        ),
    ]
