# Generated by Django 5.0.7 on 2025-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_bottomtab_link_type_alter_bottomtab_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, unique=True, verbose_name='証券コード')),
                ('name', models.CharField(max_length=200, verbose_name='銘柄名')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='33業種')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='link_type',
            field=models.CharField(choices=[('view', '内部ビュー名'), ('url', '外部リンク'), ('dummy', 'ダミーリンク')], default='view', max_length=10, verbose_name='リンクタイプ'),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='name',
            field=models.CharField(max_length=50, verbose_name='タブ名'),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='bottomtab',
            name='url_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='内部ビュー名 or URL'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='realizedtrade',
            name='name',
            field=models.CharField(max_length=100, verbose_name='銘柄名'),
        ),
        migrations.AlterField(
            model_name='realizedtrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='サブメニュー名'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
