name: Daily AI Comment
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install openai

      - name: Generate Comment
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: |
          python - <<'PY'
          import os, sys
          try:
              import openai
          except ImportError:
              sys.exit("openai モジュールが見つかりません。pip install openai が必要です。")

          api_key = os.getenv("OPENAI_API_KEY")
          model   = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

          if not api_key:
              sys.exit("❌ OPENAI_API_KEY が設定されていません。")

          from openai import OpenAI
          client = OpenAI(api_key=api_key)

          prompt = (
              "あなたは投資アドバイザーです。"
              "今日のマーケット向けに、人間っぽく、フレンドリーで少し砕けた口調で、"
              "1文のコメントを日本語で作成してください。絵文字を1〜2個添えてください。"
              "長さは60〜90文字程度。"
          )

          try:
              r = client.chat.completions.create(
                  model=model,
                  messages=[{"role": "user", "content": prompt}],
                  temperature=0.9,
                  max_tokens=120,
              )
              print("✅ 今日のコメント：", r.choices[0].message.content.strip())
          except Exception as e:
              sys.exit(f"❌ APIエラー: {e}")
          PY